---
kind: common.Image
name: image-omni-infra-provider-bare-metal
spec:
  baseImage: ghcr.io/siderolabs/talosctl:v1.8.0-alpha.1
  pushLatest: false
  extraEnvironment:
    PLATFORM: linux/amd64,linux/arm64
---
kind: common.Image
name: image-agent
spec:
  pushLatest: false
  extraEnvironment:
    PLATFORM: linux/amd64,linux/arm64
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
---
kind: golang.Generate
spec:
  versionPackagePath: internal/version
  baseSpecPath: /api
  vtProtobufEnabled: true
  specs:
    - source: api/specs/specs.proto
      subdirectory: specs
      genGateway: false
    - source: api/agent/agent.proto
      subdirectory: agent
      genGateway: true
---
kind: common.Release
name: release
spec:
  artifacts:
    - omni-infra-provider-bare-metal-*
    - agent-*
---
kind: service.CodeCov
spec:
  targetThreshold: 0
